version: "2"

services:

  samba:
    image: dperson/samba:amd64
    restart: always
    command: '-u "user;pass" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime
      - /home/pi/mnt:/gdrive
      - /home/pi/mnt/gdrive/torrent:/downloads

  plex:
    image: jaymoulin/plex:1.19.4.2935
    expose:
      - 32400
      - 33400
    hostname: ${PLEX_HOSTNAME} 
    volumes:
      - /home/pi/mnt/gdrive/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime
      - /home/pi/mnt/gdrive/Peliculas:/media/peliculas
      - /home/pi/mnt/gdrive/Series:/media/series
      - /home/pi/mnt/gdrive/tmp:/tmp
    restart: unless-stopped
    network_mode: "host" 

  transmission:
    image : jaymoulin/transmission
    command: transmission-daemon -f -g /config
    volumes:
      - /home/pi/mnt/gdrive/transmission:/config
      - /home/pi/mnt/gdrive/torrent:/downloads
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    build: flexget-a
    volumes:
      - ./flexget:/config
      - /usr/share/zoneinfo/Europe/Madrid:/etc/localtime
      - /home/pi/mnt/gdrive/torrent:/downloads
      - /home/pi/mnt/gdrive/Peliculas:/mnt/gdrive/Peliculas
      - /home/pi/mnt/gdrive/Series:/mnt/gdrive/Series
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    restart: unless-stopped
    links:
      - transmission

